export const ROUTE_NOT_FOUND = "ROUTE_ERROR_ROUTE_NOT_FOUND";
export const ALREADY_AT_DESTINATION = "ROUTE_ERROR_ALREADY_AT_DESTINATION";

export const UNKNOWN_START_STOP_INPUTED = "ROUTE_ERROR_UNKNOWN_START_STOP_INPUTED";
export const UNKNOWN_END_STOP_INPUTED = "ROUTE_ERROR_UNKNOWN_END_STOP_INPUTED";

export const ERROR_DURING_ROUTE_SEARCH = "ROUTE_ERROR_ERROR_DURING_ROUTE_SEARCH";
export const ERROR_DURING_ROUTE_RESPONSE_CONVERSION = "ERROR_DURING_ROUTE_RESPONSE_CONVERSION";