// Regular errors are caused by wrong user input. They have ERROR_ prefix
export const ERROR_ROUTE_NOT_FOUND = "ERROR_ROUTE_NOT_FOUND";
export const ERROR_ALREADY_AT_DESTINATION = "ERROR_ALREADY_AT_DESTINATION";
export const ERROR_UNKNOWN_START_STOP_INPUTED = "ERROR_UNKNOWN_START_STOP_INPUTED";
export const ERROR_UNKNOWN_END_STOP_INPUTED = "ERROR_UNKNOWN_END_STOP_INPUTED";

// Severe errors are caused due to errors in frontend code. They have ERROR_SEVERE prefix
export const ERROR_SEVERE_DURING_ROUTE_SEARCH = "ERROR_SEVERE_DURING_ROUTE_SEARCH";
export const ERROR_SEVERE_DURING_ROUTE_RESPONSE_CONVERSION = "ERROR_SEVERE_DURING_ROUTE_RESPONSE_CONVERSION";